### ISSUE TITLE
Error in matrix(as.double(X), nrow(X), ncol(X))

### ISSUE THREAD

**Issue by joqb** [BioShock38/TESS3_encho_sen#2]
Hi,

I can't get TESS3 to run my file. I tried LEA without problem, conversion from vcf works fine and I can do the analysis. To work with TESS3 I even tried to use the geno file created by LEA but it doesn't work either...

Any suggestion?

> lupulus_50.tess <- tess3("/data/filer-5-2/brassac/Martin_Humulus/160831_SN1065_0254_BC9H58ACXX_Lane6-8/renamed/humulus/humulus_090_60_outfiles/humulus_090_60.geno", lupulus.coord, K=1:20, rep=5, method="projected.ls", keep="best")
Error in matrix(as.double(X), nrow(X), ncol(X)) :
  non-numeric matrix extent
In addition: Warning message:
In matrix(as.double(X), nrow(X), ncol(X)) : NAs introduced by coercion

**Comment by francoio** [comment]
hi, 

tess3 works differently as LEA, and it doesn't take ".geno" files as input files. 

For the genotype matrix, the input file should be prepared similarly to the lfmm format (a matrix where each individual genotype is encoded as a row, and NA are "NA"). It can be obtained by using the "geno2lfmm" function of LEA. Then replace all missing genotypes by NA. Once loaded in R, use as.matrix to convert it into a numeric matrix. 

The coordinates must also be loaded in R, in the (Lon, Lat) format. Use read.table. Again convert them by using "as.matrix". 

Then, just follow the guidelines in the vignette. 

olivier
 

The next step is to read the data in R (use data.table if the matrix is big).

**Comment by francoio** [comment]
hum, something went wrong with my previous edits... tess3 requires loading the data in R. This is a difference with LEA which processes external files in the lfmm/geno format.
