### ISSUE TITLE
Color inverted between barplot and plot on map

### ISSUE THREAD

**Issue by aariani** [BioShock38/TESS3_encho_sen#5]
Great work on the implementation of this program. Also the graphic part is really good.
However by trying to analysing my data I found a discrepancy between the colours in the barplot and in the ancestry map.

I am using a population spread through North and South America. We know that there are two genetic groups with a strong signal using different population clustering analysis. One (the biggest one) in Central and the North part of South America, and the smaller one in South America 

[Barplot_TESS3.pdf](https://github.com/BioShock38/TESS3_encho_sen/files/846276/Barplot_TESS3.pdf)
 
In this barplot it seems clear that the majority of the genotypes belong to the red group (in Central and the North part of South America). However when I plot on a map the red group is mostly distributed in south America
[AncestryMap_TESS3.pdf](https://github.com/BioShock38/TESS3_encho_sen/files/846282/AncestryMap_TESS3.pdf)

I manually checked the qmatrix output of TESS3 and it seems that the clustering is more or less correct. The barplot colours are correct, just the colours of the map are reversed.

**Comment by cayek** [comment]
Hi aariani, 

I thought we fix this bug in the last commit. Do you use the last development version of tess3r ? 

You can re-install tess3r to be sure you use the last version:

```R
# install.packages("devtools")
devtools::install_github("BioShock38/TESS3_encho_sen")
```

**Comment by aariani** [comment]
Hi cayek! 
Sorry I didn't notice this fix. I was using an older version.
Thanks a lot!
